# Generated by Django 6.0.2 on 2026-02-23 09:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('completed', 'مكتمل'), ('dropped', 'منسحب'), ('expired', 'منتهي')], default='active', max_length=20, verbose_name='الحالة')),
                ('progress', models.IntegerField(default=0, help_text='من 0 إلى 100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نسبة الإنجاز %')),
                ('total_time_spent', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الوقت المستغرق (دقائق)')),
                ('certificate_issued', models.BooleanField(default=False, verbose_name='تم إصدار الشهادة')),
                ('certificate_url', models.URLField(blank=True, null=True, verbose_name='رابط الشهادة')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ البدء')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإكمال')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('last_accessed', models.DateTimeField(auto_now=True, verbose_name='آخر وصول')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course', verbose_name='الكورس')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'تسجيل',
                'verbose_name_plural': 'التسجيلات',
                'ordering': ['-enrolled_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('timestamp', models.IntegerField(blank=True, help_text='موضع الملاحظة في الفيديو', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الموضع (ثواني)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_notes', to='students.student', verbose_name='الطالب')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_notes', to='courses.video', verbose_name='الفيديو')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='enrollments.enrollment', verbose_name='التسجيل')),
            ],
            options={
                'verbose_name': 'ملاحظة',
                'verbose_name_plural': 'الملاحظات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الشهادة')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإصدار')),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='ملف الشهادة')),
                ('verification_url', models.URLField(blank=True, null=True, verbose_name='رابط التحقق')),
                ('final_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='الدرجة النهائية')),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='enrollments.enrollment', verbose_name='التسجيل')),
            ],
            options={
                'verbose_name': 'شهادة',
                'verbose_name_plural': 'الشهادات',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('time_spent', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الوقت المستغرق (دقائق)')),
                ('videos_watched', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الفيديوهات المشاهدة')),
                ('notes_added', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الملاحظات المضافة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_streaks', to='students.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'يوم تعلم',
                'verbose_name_plural': 'أيام التعلم',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='VideoProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_duration', models.IntegerField(default=0, help_text='المدة التي شاهدها الطالب بالثواني', validators=[django.core.validators.MinValueValidator(0)], verbose_name='المدة المشاهدة (ثواني)')),
                ('last_position', models.IntegerField(default=0, help_text='آخر موضع وصل إليه الطالب', validators=[django.core.validators.MinValueValidator(0)], verbose_name='آخر موضع (ثواني)')),
                ('completed', models.BooleanField(default=False, verbose_name='مكتمل')),
                ('view_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='عدد المشاهدات')),
                ('first_watched', models.DateTimeField(auto_now_add=True, verbose_name='أول مشاهدة')),
                ('last_watched', models.DateTimeField(auto_now=True, verbose_name='آخر مشاهدة')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإكمال')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_progress', to='enrollments.enrollment', verbose_name='التسجيل')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_progress', to='students.student', verbose_name='الطالب')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='courses.video', verbose_name='الفيديو')),
            ],
            options={
                'verbose_name': 'تقدم فيديو',
                'verbose_name_plural': 'تقدم الفيديوهات',
                'ordering': ['-last_watched'],
            },
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student', 'status'], name='enrollments_student_885f1d_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['course', 'status'], name='enrollments_course__f8877c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='learningstreak',
            unique_together={('student', 'date')},
        ),
        migrations.AddIndex(
            model_name='videoprogress',
            index=models.Index(fields=['student', 'completed'], name='enrollments_student_4af612_idx'),
        ),
        migrations.AddIndex(
            model_name='videoprogress',
            index=models.Index(fields=['enrollment', 'completed'], name='enrollments_enrollm_01bafb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='videoprogress',
            unique_together={('student', 'video')},
        ),
    ]
