# Generated by Django 4.2.12 on 2026-03-08 09:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='كود الكوبون')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('discount_type', models.CharField(choices=[('percentage', 'نسبة مئوية'), ('fixed', 'مبلغ ثابت')], max_length=20, verbose_name='نوع الخصم')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قيمة الخصم')),
                ('minimum_purchase', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الحد الأدنى للشراء')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('valid_from', models.DateTimeField(verbose_name='صالح من')),
                ('valid_until', models.DateTimeField(verbose_name='صالح حتى')),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد مرات الاستخدام الأقصى')),
                ('max_uses_per_user', models.PositiveIntegerField(default=1, verbose_name='عدد مرات الاستخدام لكل مستخدم')),
                ('current_uses', models.PositiveIntegerField(default=0, verbose_name='عدد مرات الاستخدام الحالية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('courses', models.ManyToManyField(blank=True, related_name='coupons', to='courses.course', verbose_name='الكورسات المحددة')),
            ],
            options={
                'verbose_name': 'كوبون خصم',
                'verbose_name_plural': 'كوبونات الخصم',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(editable=False, max_length=100, unique=True, verbose_name='رقم المعاملة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='المبلغ')),
                ('currency', models.CharField(default='EGP', max_length=3, verbose_name='العملة')),
                ('payment_method', models.CharField(choices=[('credit_card', 'بطاقة ائتمان'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('fawry', 'فوري'), ('vodafone_cash', 'فودافون كاش'), ('bank_transfer', 'تحويل بنكي')], max_length=20, verbose_name='طريقة الدفع')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('completed', 'مكتملة'), ('failed', 'فاشلة'), ('refunded', 'مسترجعة'), ('cancelled', 'ملغاة')], default='pending', max_length=20, verbose_name='الحالة')),
                ('gateway_transaction_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='رقم المعاملة من البوابة')),
                ('gateway_response', models.JSONField(blank=True, null=True, verbose_name='استجابة البوابة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإتمام')),
                ('refunded_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاسترجاع')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='courses.course', verbose_name='الكورس')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='students.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'دفعة',
                'verbose_name_plural': 'المدفوعات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='سبب الاسترجاع')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض'), ('completed', 'مكتمل')], default='pending', max_length=20, verbose_name='الحالة')),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ المسترجع')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات الإدارة')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإتمام')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refund', to='payments.payment', verbose_name='الدفعة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_requests', to='students.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'طلب استرجاع',
                'verbose_name_plural': 'طلبات الاسترجاع',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ الخصم')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاستخدام')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='payments.coupon', verbose_name='الكوبون')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usage', to='payments.payment', verbose_name='الدفعة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to='students.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'استخدام كوبون',
                'verbose_name_plural': 'استخدامات الكوبونات',
                'ordering': ['-used_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['student', 'status'], name='payments_pa_student_2663d2_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_id'], name='payments_pa_transac_8e9d99_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'created_at'], name='payments_pa_status_343680_idx'),
        ),
    ]
