# Generated by Django 4.2.12 on 2026-03-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_loginhistory_device_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'ملف شخصي', 'verbose_name_plural': 'ملفات شخصية'},
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='accounts_us_email_74c8d6_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='accounts_us_usernam_c0ea66_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='accounts_us_role_1fa9a5_idx',
        ),
        migrations.RemoveField(
            model_name='loginhistory',
            name='device_fingerprint',
        ),
        migrations.RemoveField(
            model_name='loginhistory',
            name='device_name',
        ),
        migrations.RemoveField(
            model_name='loginhistory',
            name='is_suspicious',
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='device_info',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='معلومات الجهاز'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الدولة'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'ذكر'), ('female', 'أنثى'), ('other', 'آخر')], max_length=10, null=True, verbose_name='الجنس'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True, verbose_name='لينكدإن'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='show_email',
            field=models.BooleanField(default=False, verbose_name='إظهار البريد'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='show_phone',
            field=models.BooleanField(default=False, verbose_name='إظهار الهاتف'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='website_url',
            field=models.URLField(blank=True, null=True, verbose_name='الموقع الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
