# Generated by Django 4.2.12 on 2026-03-08 09:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollments', '0001_initial'),
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الامتحان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('instructions', models.TextField(blank=True, null=True, verbose_name='تعليمات الامتحان')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('published', 'منشور'), ('archived', 'مؤرشف')], default='draft', max_length=20, verbose_name='الحالة')),
                ('duration', models.IntegerField(help_text='المدة بالدقائق', validators=[django.core.validators.MinValueValidator(1)], verbose_name='مدة الامتحان (دقائق)')),
                ('passing_score', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درجة النجاح %')),
                ('max_attempts', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)], verbose_name='عدد المحاولات المسموحة')),
                ('shuffle_questions', models.BooleanField(default=False, verbose_name='خلط الأسئلة')),
                ('shuffle_answers', models.BooleanField(default=False, verbose_name='خلط الإجابات')),
                ('show_result_immediately', models.BooleanField(default=True, verbose_name='إظهار النتيجة فوراً')),
                ('show_correct_answers', models.BooleanField(default=False, verbose_name='إظهار الإجابات الصحيحة')),
                ('allow_review', models.BooleanField(default=True, verbose_name='السماح بمراجعة الإجابات')),
                ('is_open', models.BooleanField(default=True, verbose_name='مفتوح يدوياً')),
                ('available_from', models.DateTimeField(blank=True, null=True, verbose_name='متاح من')),
                ('available_until', models.DateTimeField(blank=True, null=True, verbose_name='متاح حتى')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='courses.course', verbose_name='الكورس')),
            ],
            options={
                'verbose_name': 'امتحان',
                'verbose_name_plural': 'الامتحانات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'جاري'), ('submitted', 'تم التسليم'), ('expired', 'منتهية المدة'), ('graded', 'تم التصحيح')], default='in_progress', max_length=20, verbose_name='الحالة')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='الدرجة %')),
                ('points_earned', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='النقاط المكتسبة')),
                ('passed', models.BooleanField(default=False, verbose_name='ناجح')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت البدء')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت التسليم')),
                ('expires_at', models.DateTimeField(verbose_name='وقت الانتهاء')),
                ('attempt_number', models.IntegerField(default=1, verbose_name='رقم المحاولة')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to='enrollments.enrollment', verbose_name='التسجيل')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exams.exam', verbose_name='الامتحان')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to='students.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'محاولة امتحان',
                'verbose_name_plural': 'محاولات الامتحانات',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='نص السؤال')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'اختيار من متعدد'), ('true_false', 'صح أو خطأ'), ('multiple_select', 'اختيار متعدد')], default='multiple_choice', max_length=20, verbose_name='نوع السؤال')),
                ('image', models.ImageField(blank=True, null=True, upload_to='exams/questions/', verbose_name='صورة السؤال')),
                ('points', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='درجة السؤال')),
                ('order', models.IntegerField(default=0, verbose_name='ترتيب السؤال')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='شرح الإجابة')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.exam', verbose_name='الامتحان')),
            ],
            options={
                'verbose_name': 'سؤال',
                'verbose_name_plural': 'الأسئلة',
                'ordering': ['exam', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=500, verbose_name='نص الإجابة')),
                ('is_correct', models.BooleanField(default=False, verbose_name='إجابة صحيحة')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.question', verbose_name='السؤال')),
            ],
            options={
                'verbose_name': 'إجابة',
                'verbose_name_plural': 'الإجابات',
                'ordering': ['question', 'order'],
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False, verbose_name='إجابة صحيحة')),
                ('points_earned', models.IntegerField(default=0, verbose_name='النقاط المكتسبة')),
                ('answered_at', models.DateTimeField(auto_now=True, verbose_name='وقت الإجابة')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='exams.examattempt', verbose_name='المحاولة')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.question', verbose_name='السؤال')),
                ('selected_answers', models.ManyToManyField(blank=True, to='exams.answer', verbose_name='الإجابات المختارة')),
            ],
            options={
                'verbose_name': 'إجابة طالب',
                'verbose_name_plural': 'إجابات الطلاب',
                'unique_together': {('attempt', 'question')},
            },
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['exam', 'order'], name='exams_quest_exam_id_4ac027_idx'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['student', 'exam'], name='exams_exama_student_ce1bfc_idx'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['status'], name='exams_exama_status_6897fc_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['course', 'status'], name='exams_exam_course__7ff870_idx'),
        ),
    ]
