# Generated by Django 4.2.12 on 2026-03-09 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_coursecomment_is_hidden'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='coursecomment',
            new_name='courses_cou_course__7de288_idx',
            old_name='courses_cou_course__idx',
        ),
        migrations.RemoveField(
            model_name='coursecomment',
            name='is_hidden',
        ),
    ]
