# Generated by Django 6.0.2 on 2026-02-23 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='نبذة تعريفية')),
                ('specialization', models.CharField(blank=True, max_length=200, null=True, verbose_name='التخصص')),
                ('years_of_experience', models.PositiveIntegerField(default=0, verbose_name='سنوات الخبرة')),
                ('website', models.URLField(blank=True, null=True, verbose_name='الموقع الشخصي')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
                ('github', models.URLField(blank=True, null=True, verbose_name='GitHub')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='instructors/avatars/', verbose_name='الصورة الشخصية')),
                ('resume', models.FileField(blank=True, null=True, upload_to='instructors/resumes/', verbose_name='السيرة الذاتية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مميز')),
                ('total_courses', models.PositiveIntegerField(default=0, verbose_name='عدد الكورسات')),
                ('total_students', models.PositiveIntegerField(default=0, verbose_name='عدد الطلاب')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='متوسط التقييم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'instructor'}, on_delete=django.db.models.deletion.CASCADE, related_name='instructor_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'مدرب',
                'verbose_name_plural': 'المدربون',
                'ordering': ['-created_at'],
            },
        ),
    ]
