# Generated by Django 6.0.2 on 2026-02-23 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('priority', models.CharField(choices=[('low', 'منخفضة'), ('medium', 'متوسطة'), ('high', 'عالية'), ('urgent', 'عاجلة')], default='medium', max_length=20, verbose_name='الأولوية')),
                ('target_audience', models.CharField(choices=[('all', 'الجميع'), ('students', 'الطلاب فقط'), ('instructors', 'المدرسين فقط')], default='all', max_length=20, verbose_name='الفئة المستهدفة')),
                ('is_published', models.BooleanField(default=False, verbose_name='منشور')),
                ('publish_at', models.DateTimeField(blank=True, null=True, verbose_name='موعد النشر')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='موعد الانتهاء')),
                ('send_notification', models.BooleanField(default=True, verbose_name='إرسال إشعار')),
                ('send_email', models.BooleanField(default=False, verbose_name='إرسال إيميل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة')),
            ],
            options={
                'verbose_name': 'إعلان',
                'verbose_name_plural': 'الإعلانات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='الموضوع')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('sent', 'تم الإرسال'), ('failed', 'فشل')], default='pending', max_length=20, verbose_name='الحالة')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='رسالة الخطأ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإرسال')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل إيميل',
                'verbose_name_plural': 'سجل الإيميلات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_in_app', models.BooleanField(default=True, verbose_name='تفعيل إشعارات التطبيق')),
                ('enable_email', models.BooleanField(default=True, verbose_name='تفعيل إشعارات البريد')),
                ('notify_course_updates', models.BooleanField(default=True, verbose_name='تحديثات الكورسات')),
                ('notify_exam_results', models.BooleanField(default=True, verbose_name='نتائج الامتحانات')),
                ('notify_payments', models.BooleanField(default=True, verbose_name='المدفوعات')),
                ('notify_announcements', models.BooleanField(default=True, verbose_name='الإعلانات')),
                ('notify_reminders', models.BooleanField(default=True, verbose_name='التذكيرات')),
                ('email_frequency', models.CharField(choices=[('instant', 'فوري'), ('daily', 'يومي'), ('weekly', 'أسبوعي')], default='instant', max_length=20, verbose_name='تكرار إرسال الإيميل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تفضيلات الإشعارات',
                'verbose_name_plural': 'تفضيلات الإشعارات',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('course_enrolled', 'تسجيل في كورس'), ('course_completed', 'إكمال كورس'), ('exam_result', 'نتيجة امتحان'), ('payment_success', 'دفع ناجح'), ('payment_failed', 'دفع فاشل'), ('refund_approved', 'موافقة على استرجاع'), ('refund_rejected', 'رفض استرجاع'), ('new_course', 'كورس جديد'), ('course_update', 'تحديث كورس'), ('announcement', 'إعلان'), ('reminder', 'تذكير'), ('system', 'نظام')], max_length=30, verbose_name='نوع الإشعار')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('link', models.CharField(blank=True, max_length=500, null=True, verbose_name='الرابط')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='بيانات إضافية')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروء')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت القراءة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'), models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx')],
            },
        ),
    ]
